### ISSUE TITLE
Allow boot_file to be specified in the config

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-project/erlinit#11]
Currently, erlinit will look for boot files in the release dir and if there are multiple boot files present it will choose the first on for booting. 
https://github.com/nerves-project/erlinit/blob/3c7a1134d20fc9823e52ac2ec94d7c5b9816576f/src/erlinit.c#L133-L134

There are changes I would like to make to the nerves_runtime which would require that the initial boot file can be specified in the erlinit configuration. This is because this directory will contain more than one boot file but should not always choose the first one. 

I think we can safely default to the current behaviour if no boot file is specified in the config

**Comment by fhunleth** [comment]
I made the change in a branch: https://github.com/nerves-project/erlinit/tree/boot_file

I added a `-b` parameter (long option is `--boot`) where you can specify the boot file name. This can be a relative path to the release and you don't need a `.boot` at the end. The README.md has more info and I add a few tests that might give more info for how it works.

Let me know if this is what you want and I'll merge and create a release.

**Comment by mobileoverlord** [comment]
I have tested this using qemu_arm and can confirm that it successfully booted my machine using the passed bootscript in the `erlinit.config` file. I have also found that if the bootscript did not exist, it failed back to autodiscovery logic. Thanks for getting this in quickly :)

**Comment by fhunleth** [comment]
Thanks for testing! The change will be in the v0.8.0 release.
