### ISSUE TITLE
Add option to dump dmesg (/dev/kmsg) to a file before reboot

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/erlinit#17]
This will make it easier to debug systems where the debug serial port isn't normally connected. For example, the USB gadget mode devices like the Raspberry Pi 0 and BBB fit this case.

**Comment by fhunleth** [comment]
I'm leaning towards encouraging the use of the pstore driver instead of adding more to erlinit.

**Comment by mobileoverlord** [comment]
I agree with using pstore. It seems like a better fit.

**Comment by fhunleth** [comment]
I missed closing this when `--shutdown-report` was added. It's been in `erlinit` since v1.8.0 (~10 months ago).
