### ISSUE TITLE
Add support for heart and hardware watchdog timers

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/erlinit#2]
For systems with built-in watchdog timers, it would be nice if Erlang could pet them automatically. One such system is the Intel Edison which starts its watchdog at boot. Perhaps `heart` could be used to pet the watchdog timer: http://erlang.org/doc/man/heart.html.

**Comment by mobileoverlord** [comment]
We could probably close this issue with the recent addition of https://github.com/nerves-project/nerves_heart unless there is interest in moving the functionality up further into erlinit.

**Comment by fhunleth** [comment]
Thanks. I missed this.
