### ISSUE TITLE
RFC: rootdisk convention - to 0 or not to 0?

### ISSUE THREAD

**Issue by electricshaman** [nerves-project/erlinit#21]
Discussion started here: https://github.com/nerves-project/nerves_system_x86_64/commit/43d2d285105f545ad07f0472db315949ea577313#commitcomment-25888887

**Comment by fhunleth** [comment]
I'm cool with `/dev/rootdisk0`, `/dev/rootdisk0p1`, etc. Let me know if you are too and I'll merge and make a release.

**Comment by fhunleth** [comment]
Thanks for bringing the topic up. See `v1.3.1` (patch release, but my guess is that yours is the only company using the rootdisk feature since it is so new.)
