### ISSUE TITLE
rootdisk symlinks not created for nvme disk

### ISSUE THREAD

**Issue by AlmiS** [nerves-project/erlinit#39]
I have an Intel NUC which boots fine when booting nerves from usb, but when booting from an internal nvme ssd the rootdisk symlinks are not creted.

Looking in /dev i see the disk properly listed as block device 'nvme0n1' and partitions 1 to 4 as 'nvme0n1p*'. However, there are no '/dev/rootdisk0p*' symlinks, and no errors in dmesg or RingLogger regarding the creation of the links. 

Since there are no error messages i suspect the error might be that the loop on line 143 of fs.c does not properly detect an instance of the root device.

**Comment by fhunleth** [comment]
I think I found the issue, but I don't have an Intel NUC or any NVME board to test it against.

Do you think that you could verify the fix? Depending on your setup, this might not be easy. If you're building a custom system and have access to the `build/erlinit-x.y.z` directory, you can update the fs.c, and run `make erlinit-rebuild all`. If not, I'll post a prebuilt executable that you can put in your projects `rootfs_overlay` to override the existing one.

**Comment by AlmiS** [comment]
Thanks for the quick response! 
If you can provide me with the prebuilt executable, I will verify the fix tomorrow when I get back to my office.

**Comment by fhunleth** [comment]
Here's the file:

[init.gz](https://github.com/nerves-project/erlinit/files/2489658/init.gz)

`gunzip` it and put it in the `rootfs_overlay/sbin` directory

**Comment by AlmiS** [comment]
I added the gunzipped file under rootfs_overlay/sbin of my nerves app, but it seems the init will not launch at all. During boot I get stuck in a shell, where instead the init program should have been launched. The /sbin/init pogram is there, but i cannot launch it from the shell either.

Using the precompiled init, this happens regardless of disk type (usb or nvme).

Can it be because it is not compiled with the same nerves toolchain as we use? We use `nerves_toolchain_x86_64_unknown_linux_gnu: 1.1.0`.

Would it make a difference whatever i put the init in the overlay of my custom x86 based system, rather than the nerves app?

**Comment by AlmiS** [comment]
I managed to make it work by manually editing `fs.c` and running `make erlinit-rebuild all` as you sugessted initially.

I can confirm that the fix you did is working.
Thank you.

**Comment by fhunleth** [comment]
Great! Thanks for verifying. I'll propagate the change so that it will appear in the next system release.
