### ISSUE TITLE
`--run-on-exit` doesn't prevent reboot on exit

### ISSUE THREAD

**Issue by dzfranklin** [nerves-project/erlinit#92]
### Environment

* Elixir version (`elixir -v`): 
```Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

* Nerves environment: (`mix nerves.env --info`)
```
==> nerves
==> niss_fw
|nerves_bootstrap| Environment Package List

  No packages found
|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   host
  MIX_ENV:      dev

NERVES_SYSTEM is unset
NERVES_TOOLCHAIN is unset
|nerves_bootstrap| Environment Variable List
  target:     host
  toolchain:  unset
  system:     unset
  app:        .

|nerves_bootstrap| Loadpaths End
```

* Additional information about your host, target hardware or environment that
  may help

target is rpi4

### Current behavior

When connected over UART:

```
iex(1)> exit
*** ERROR: Shell process terminated! (^G to start new job) ***
[I press ^G]

User switch command
 --> q

[nbtty: terminating]
#[  152.277627] reboot: Restarting system
```

### Expected behavior

Instead of `Restarting system` I am dropped into a shell prompt.

**Comment by LostKobrakai** [comment]
Just saw this. I've made the documentation more explicit about this recently: https://github.com/nerves-project/erlinit/pull/105

**Comment by fhunleth** [comment]
@LostKobrakai Thanks for posting your response about `heart` since that makes a lot of sense for what happened here. And then if `heart` didn't reboot, the watchdog timer would have rebooted. Both have to be disabled to be able to use `--run-on-exit`.
